services:
  postgres:
    image: postgres:latest
    platform: linux/amd64
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 30s
      interval: 10s
      retries: 2
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

  webserver:
    image: my-airflow:latest
    ports:
      - "8080:8080"
    entrypoint: ["sh", "-c", "airflow db migrate && airflow webserver"]
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres
      - redis

  scheduler:
    image: my-airflow:latest
    command: ["scheduler"]
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
    depends_on:
      - webserver

  worker-1:
    image: my-airflow:latest
    command:
      - "celery"
      - "worker"
      - "--autoscale=16,4"
      - "--queues=default,worker-1"
      - "--celery-hostname=worker-1@%h"
      - "--skip-serve-logs"
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
    depends_on:
      - scheduler

  worker-2:
    image: my-airflow:latest
    command:
      - "celery"
      - "worker"
      - "--autoscale=16,4"
      - "--queues=default,worker-2"
      - "--celery-hostname=worker-2@%h"
      - "--skip-serve-logs"
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
    depends_on:
      - scheduler

  flower:
    image: my-airflow:latest
    command: ["celery", "flower", "--port", "5555"]
    ports:
      - "5555:5555"
    depends_on:
      - worker-1
      - worker-2

  triggerer:
    image: my-airflow:latest
    command: ["triggerer"]
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
    depends_on:
      - scheduler

volumes:
  logs:
