services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - airflow
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 30s
      interval: 10s
      retries: 2
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks:
      - airflow
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

  webserver:
    image: my-airflow:latest
    build:
      pull: false
    ports:
      - "8080:8080"
    entrypoint: ["sh", "-c", "airflow db migrate && airflow webserver"]
    networks:
      - airflow
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres
      - redis

  scheduler:
    image: my-airflow:latest
    build:
      pull: false
    command: ["scheduler"]
    networks:
      - airflow
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
    depends_on:
      - webserver

  worker:
    image: my-airflow:latest
    build:
      pull: false
    command: ["celery", "worker"]
    networks:
      - airflow
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
    depends_on:
      - scheduler

  triggerer:
    image: my-airflow:latest
    build:
      pull: false
    command: ["triggerer"]
    networks:
      - airflow
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
    depends_on:
      - scheduler

volumes:
  logs:

networks:
  airflow:
    driver: bridge
